# frozen_string_literal: true

module BranchEnv
  class Environment
    def initialize(runner:)
      @runner = runner
    end

    def write_env_file(worktree_path, app_host:, port:, dev_db:, test_db:, base_env_file:)
      env_path = File.join(worktree_path, ".env")
      puts "Writing .env"

      content = <<~ENV
        APP_HOST=#{app_host}
        ASSET_HOST=http://#{app_host}
        BASE_DOMAIN=#{app_host}
        PORT=#{port}
        DEV_DB=#{dev_db}
        TEST_DB=#{test_db}

      ENV

      content += File.read(base_env_file)
      content += "\n"

      if @runner.dry_run?
        puts "  [dry-run] Would write .env"
      else
        File.write(env_path, content)
      end

      env_path
    end

    def write_envrc_file(worktree_path, app_host:, port:, dev_db:, test_db:, base_env_file:)
      envrc_path = File.join(worktree_path, ".envrc")
      puts "Writing .envrc"

      content = <<~ENVRC
        # Generated by branch-env
        set -a

        # Common per-branch variables
        export APP_HOST=#{app_host}
        export ASSET_HOST=https://#{app_host}
        export BASE_DOMAIN=#{app_host}
        export PORT=#{port}
        export DEV_DB=#{dev_db}
        export TEST_DB=#{test_db}

      ENVRC

      content += File.read(base_env_file)
      content += "\nset +a\n"

      if @runner.dry_run?
        puts "  [dry-run] Would write .envrc"
      else
        File.write(envrc_path, content)
      end

      envrc_path
    end

    def allow_direnv(worktree_path)
      return unless command_exists?("direnv")

      puts "Allowing direnv..."
      @runner.run!("direnv", "allow", chdir: worktree_path) rescue nil
    end

    def copy_files(worktree_path, copy_files_dir:)
      return unless copy_files_dir
      return unless File.directory?(copy_files_dir)

      puts "Copying files from #{copy_files_dir}"

      Dir.glob(File.join(copy_files_dir, "**", "*"), File::FNM_DOTMATCH).each do |source|
        next if File.directory?(source)
        next if File.basename(source) == "." || File.basename(source) == ".."

        relative_path = source.sub("#{copy_files_dir}/", "")
        dest = File.join(worktree_path, relative_path)

        if @runner.dry_run?
          puts "  [dry-run] Would copy #{relative_path}"
        else
          FileUtils.mkdir_p(File.dirname(dest))
          FileUtils.cp(source, dest)
          puts "  Copied #{relative_path}"
        end
      end
    end

    def create_symlinks(worktree_path, symlinks:)
      return unless symlinks

      symlinks.each do |link|
        source = link["source"]
        dest_relative = link["dest"]

        unless File.exist?(source)
          puts "  Skipping symlink #{dest_relative} (source not found: #{source})"
          next
        end

        dest = File.join(worktree_path, dest_relative)

        if @runner.dry_run?
          puts "  [dry-run] Would symlink #{dest_relative} -> #{source}"
        else
          FileUtils.mkdir_p(File.dirname(dest))
          FileUtils.rm_rf(dest) if File.exist?(dest) || File.symlink?(dest)
          FileUtils.ln_s(source, dest)
          puts "  Symlinked #{dest_relative} -> #{source}"
        end
      end
    end

    private

    def command_exists?(cmd)
      system("command -v #{cmd} >/dev/null 2>&1")
    end
  end
end
